name: Publish docker image

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build-publish-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Read version from package.json
        id: read_version_from_file
        run: |
          VERSION=$(cat VERSION)
          echo "::set-output name=version::$VERSION"
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          target: server
          push: true
          tags: |
            l1ghth4t/immunity-iast:${{ steps.read_version_from_file.outputs.version }}
            l1ghth4t/immunity-iast:latest
            
  build-publish-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Read version from package.json
        id: read_version_from_file
        run: |
          VERSION=$(cat VERSION)
          echo "::set-output name=version::$VERSION"
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          target: worker
          push: true
          tags: |
            l1ghth4t/immunity-iast-worker:${{ steps.read_version_from_file.outputs.version }}
            l1ghth4t/immunity-iast-worker:latest
